tmux_conf_new_session_retain_current_path=true

# Prefix: C-s
set -g prefix ^s

# Elegant Vagrant

theme_bg="#000000"
theme_fg="#d9d9d9"
theme_cyan="#00b29e"
theme_black="#1c1f24"
theme_gray="#202020"
theme_magenta="#7c5cff"
theme_pink="#f067fc"
theme_red="#fc2025"
theme_green="#02f789"
theme_blue="#5ffcfc"
theme_black4="#101010"

set-option -g status-position "top"
set -g status "on"
set -g status-bg "${theme_bg}"
set -g status-justify "left"
set -g status-left-length "100"
set -g status-right-length "100"
set -g message-style "fg=${theme_magenta},bg=${theme_gray},align=centre"
set -g message-command-style "fg=${theme_magenta},bg=${theme_gray},align=centre"
set -g pane-border-style "fg=${theme_blue}"
set -g pane-active-border-style "fg=${theme_magenta}"
set -g window-status-activity-style "fg=${theme_fg},bg=${theme_bg},none"
set -g window-status-separator ""
set -g window-status-style "fg=${theme_fg},bg=${theme_bg},none"
set -g window-status-current-format "#[fg=${theme_blue},bg=${theme_bg}] #I: #[fg=${theme_magenta},bg=${theme_bg}]#W#[fg=${theme_magenta},bg=${theme_bg}]#{?window_zoomed_flag, 󰊓,}"
set -g window-status-format "#[fg=${theme_blue},bg=${theme_bg}] #I: #[fg=${theme_fg},bg=${theme_bg}]#W"
set -g status-right "#[fg=${theme_blue},bg=${theme_bg},nobold,nounderscore,noitalics]#[fg=${theme_bg},bg=${theme_blue},nobold,nounderscore,noitalics] #[fg=${theme_fg},bg=${theme_gray}] #(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) #{?client_prefix,#[fg=${theme_magenta}],#[fg=${theme_magenta}]}#[bg=${theme_gray}]#{?client_prefix,#[bg=${theme_magenta}],#[bg=${theme_green}]}#[fg=${theme_bg}] #[fg=${theme_fg},bg=${theme_gray}] #S "
set -g status-left ""
set -g clock-mode-colour "${theme_blue}"
set -g mode-style "fg=${theme_blue} bg=${theme_black4} bold"

# QoL

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

set -g renumber-windows on
set -gq allow-passthrough on
set -g visual-activity off
set -g visual-bell off
set -g visual-silence off
setw -g monitor-activity on
set -g bell-action none

set -g mouse on
set -g set-clipboard on
set-option -sg escape-time 10

# Bindings

set-window-option -g mode-keys vi

unbind '"'
unbind %
unbind v
unbind -T copy-mode-vi g

bind-key -n Home send-keys C-a
bind-key -n End send-keys C-e

bind C-n next-window

bind r source-file ~/.tmux.conf \; display "Config reloaded!"

bind C-s run-shell 'bash -c "~/.local/bin/tmux-manager"'   # Sessions
bind C-d run-shell 'bash -c "~/.local/bin/tmux-manager d"' # Directories
bind C-f run-shell 'bash -c "~/.local/bin/tmux-manager f"' # Tmuxp
bind C-z run-shell 'bash -c "~/.local/bin/tmux-manager z"' # Zoxide

bind C-h select-pane -L
bind C-j select-pane -D
bind C-k select-pane -U
bind C-l select-pane -R

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

bind C-y new-session -t "scratch"

bind C-k kill-pane

bind v copy-mode
bind-key -T copy-mode-vi 'Escape' send -X cancel
bind-key -T copy-mode-vi 'v' send -X begin-selection
bind-key -T copy-mode-vi 'g' switch-client -T copy-mode-extended
bind-key -T copy-mode-extended 'h' send -X start-of-line \; switch-client -T copy-mode-vi
bind-key -T copy-mode-extended 'l' send -X end-of-line \; switch-client -T copy-mode-vi
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle

# X11 and Wayland
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "xclip -sel clip"
# bind -T copy-mode-vi y send -X copy-pipe-and-cancel "wl-copy"

# Neovim Integration

is_nvim="ps -o state= -o comm= -t '#{pane_tty}' \
    | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?n?vim$'"

bind-key C-h if-shell "$is_nvim" 'send-keys C-h' 'select-pane -L'
bind-key C-j if-shell "$is_nvim" 'send-keys C-j' 'select-pane -D'
bind-key C-k if-shell "$is_nvim" 'send-keys C-k' 'select-pane -U'
bind-key C-l if-shell "$is_nvim" 'send-keys C-l' 'select-pane -R'
