#!/usr/bin/env bash

# Tools

export EDITOR=nvim
export PAGER=bat
export SHELL=zsh
export TERMCMD=alacritty
export VISUAL=nvim

# Directories

export OBSIDIAN=$HOME/obsidian/
export JOURNAL=$OBSIDIAN/journal/Journals/
export MUSIC="$HOME/music/"
export PASSWORD_STORE_DIR="$HOME/.password-store/"
