#!/usr/bin/env bash

# === Command Replacement ===

alias cp="rsync -avz --update"

# === Override Default Flags ===

alias diff="diff --color=auto"
alias dmenu="dmenu -nf '#ffffff' -nb '#000000' -sb '#1c1c1f' -sf '#7c5cff'"
alias grep="grep --color=auto"
alias ip="ip -color=auto"
alias ln="ln -v"
alias ls='ls --color=auto --group-directories-first'
alias mv="mv -v"
alias rclone="rclone --verbose"
alias rm="rm -v"
alias rsync="rsync -azrPl"
alias vidir="vidir --verbose"

# === Shortcuts ===

# simple way to check local devices
alias nethunter='nmap -v -sn 192.168.0.1/24 | grep -v "host down"'
# ssh over adb for termux
alias sshadb="adb forward tcp:8022 tcp:8022; ssh localhost -p 8022"
# sxhkd
alias sxh='nvim $HOME/.config/sxhkd/sxhkdrc'

alias e='emacs'

alias lg='nvim +Neogit'
alias d="nvim +Oil"
alias v='nvim'

alias t='tree'

alias bb="bmark -r list | fzf -m | xargs -I {} xdg-open '{}'"
alias sm="sshmanager"

# === Distros ===

distro=$(cat ~/.config/distro 2>/dev/null)
case "$distro" in
debian)
  export SUDO=sudo
  alias pkg-autoremove="\$SUDO apt autoremove" \
    pkg-autoclean="\$SUDO apt autoclean" \
    pkg-add="\$SUDO pkg install" \
    pkg-del="\$SUDO pkg uninstall" \
    pkg-update="\$SUDO pkg update" \
    pkg-upgrade="\$SUDO pkg upgrade"
  ;;
termux)
  alias pkg-autoremove='apt autoremove' \
    pkg-autoclean='apt autoclean' \
    pkg-add='pkg install' \
    pkg-del='pkg uninstall' \
    pkg-update='pkg update' \
    pkg-upgrade='pkg upgrade'

    # Circumventing the error:
    # "executable's TLS segment is underaligned:
    # alignment is 8, needs to be at least 64 for ARM64 Bionic"
    odin_build() {
      odin build $@ -reloc-mode:pic -no-thread-local
    }
  ;;
artix)
  export SUDO=doas
  alias pkg-autoremove="pacman -Qdtq | \$SUDO pacman -Rns -" \
    pkg-autoclean="\$SUDO pacman -Scc" \
    pkg-add="\$SUDO pacman -S" \
    pkg-del="\$SUDO pacman -Rns" \
    pkg-update="\$SUDO pacman -Syy" \
    pkg-upgrade="\$SUDO pacman -Syu"
  ;;
*)
  [ -z "$distro" ] && echo "Distro not set"
  [ -n "$distro" ] && echo "Distro not supported"
  ;;
esac
