#!/usr/bin/env bash

# === Command Replacement ===

# Replaces full commands to alternative ones
alias \
  cp="rsync -avz --update" \
  la='eza --color=auto --group-directories-first -a' \
  lda='eza --color=auto --group-directories-first -Da' \
  ld='eza --color=auto --group-directories-first -D' \
  ll='eza --color=auto --group-directories-first -l' \
  ls='eza --color=auto --group-directories-first'

# === Override Default Flags ===

# Sets default flags to common commands
alias \
  diff="diff --color=auto" \
  grep="grep --color=auto" \
  ip="ip -color=auto" \
  lynx="lynx -cookies -cfg \$HOME/.config/lynxrc" \
  mv="mv -v" \
  rclone="rclone --verbose" \
  rm="rm -v" \
  rsync="rsync -azrPl" \
  vidir="vidir --verbose"

# === Command Shortcuts ===

# Shortcuts to longer commands
alias \
  ctrash='gio trash --empty' \
  dmenu="dmenu -b -nf '#ffffff' -nb '#000000' -sb '#1c1c1f' -sf '#7c5cff'" \
  historyc="rm \$HOME/.zsh_history" \
  lgd="doppel \$HOME/dotfiles/ -exec lazygit" \
  lg='lazygit' \
  mks="sudo make clean install" \
  nethunter='nmap -v -sn 192.168.0.1/24 | grep -v "host down"' \
  sshadb="adb forward tcp:8022 tcp:8022; ssh localhost -p 8022" \
  sxh='nvim $HOME/.config/hypr/modules/keybinds.conf' \
  t='task' \
  vim='nvim' \
  v='nvim'

# === Script Shortcuts ===

# Shortcuts to longer scripts made by me
alias \
  bb="bmark -r list | fzf -m | xargs -I {} xdg-open '{}'" \
  jnd="jn journal day Journals/Daily" \
  o="obsidian-helper" \
  rr="ranger_cd" \
  sear="python \$PYTHONPATH/sear.py" \
  sm="sshmanager" \
  s="search -s" \
  tt="taskwarrior-helper"

# === Distros ===

# Arch Linux

if command -v pacman &>/dev/null; then
  alias autoremove='pacman -Qdtq | sudo pacman -Rns -' \
    clearcache='pacman -Scc' \
    install='sudo pacman -S' \
    remove='sudo pacman -Rns' \
    update='sudo pacman -Syy' \
    upgrade='sudo pacman -Syu' \
    sshd='sudo systemctl start sshd' \
    hx='helix'
fi

# Alpine Linux

if command -v apk &>/dev/null; then
  alias install='doas apk add' \
    remove='doas apk del' \
    update='doas apk update' \
    upgrade='doas apk upgrade' \
    fix='doas apk fix'
fi

# NixOS

if [ -n "$NIX_PATH" ]; then
  # This alias expects to receive a just recipe
  alias nx="cd \$HOME/nix/; just"
fi

# Termux

if [ -n "$TERMUX_VERSION" ]; then
  alias autoremove='apt autoremove' \
    install='pkg install' \
    remove='pkg uninstall' \
    update='pkg update' \
    upgrade='pkg upgrade'
fi

# === Networking ===

if command -v nmap >/dev/null; then
  alias nmap_open_ports="nmap --open" \
    nmap_list_interfaces="nmap --iflist" \
    nmap_slow="sudo nmap -sS -v -T1" \
    nmap_fin="sudo nmap -sF -v" \
    nmap_full="sudo nmap -sS -T4 -PE -PP -PS80,443 -PY -g 53 -A -p1-65535 -v" \
    nmap_check_for_firewall="sudo nmap -sA -p1-65535 -v -T4" \
    nmap_ping_through_firewall="nmap -PS -PA" \
    nmap_fast="nmap -F -T5 --version-light --top-ports 300" \
    nmap_detect_versions="sudo nmap -sV -p1-65535 -O --osscan-guess -T4 -Pn" \
    nmap_check_for_vulns="nmap --script=vuln" \
    nmap_full_udp="sudo nmap -sS -sU -T4 -A -v -PE -PS22,25,80 -PA21,23,80,443,3389 " \
    nmap_traceroute="sudo nmap -sP -PE -PS22,25,80 -PA21,23,80,3389 -PU -PO --traceroute " \
    nmap_full_with_scripts="sudo nmap -sS -sU -T4 -A -v -PE -PP -PS21,22,23,25,80,113,31339 -PA80,113,443,10042 -PO --script all " \
    nmap_web_safe_osscan="sudo nmap -p 80,443 -O -v --osscan-guess --fuzzy " \
    nmap_ping_scan="nmap -n -sP"
fi
